[package]
name = "diff"
version = "0.1.0"
authors = ["RoeiRaz <m.roei.raz@gmail.com>"]
edition = "2018"

[dependencies]
unicode-segmentation = "1.2.1"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
clap = "2.33.0"